#!/usr/bin/env groovy

node('emulator'){
      stage('Build') {
                sh 'sudo chown dina:dina /dev/kvm'
            
                      }
        stage('Test') {

       sh 'sudo chown dina:dina /dev/kvm'
                      } 
     stage('Deliver') {
                sh '''
                chmod a+x ./gradlew
                ./gradlew connectedAndroidTest --info
                adb devices 
                pwd
                adb install -r app/build/outputs/apk/app-debug-androidTest.apk
                '''
                     }
stage('connect to mc'){         
	
 

	def response = httpRequest requestBody: 'string' , acceptType: 'APPLICATION_JSON', contentType: 'APPLICATION_JSON', httpMode: 'POST', url: "https://hpmc12.mobilecenter.io/rest/client/login", customHeaders: [name: 'Content-Type', value: 'application/json'], consoleLogResponseBody: true

         }
}
