#!/usr/bin/env groovy
import groovy.json.JsonSlurper
import groovy.json.JsonOutput


node('emulator'){
      stage('Build') {
                sh 'sudo chown dina:dina /dev/kvm'
            
                      }
        stage('Test') {

       sh 'sudo chown dina:dina /dev/kvm'
                      } 
     stage('Deliver') {
                sh '''
                chmod a+x ./gradlew
                ./gradlew connectedAndroidTest --info
                adb devices 
                pwd
                adb install -r app/build/outputs/apk/app-debug-androidTest.apk
                '''
                     }
stage('connect to mc'){         
	def myJson = '{"name":"ahmed.abdelhamid2@vodafone.com","password":"Voda@123"}'

def response = httpRequest requestBody:  groovy.json.JsonOutput.toJson(myJson), acceptType: 'APPLICATION_JSON', contentType: 'APPLICATION_JSON', httpMode: 'POST', url: "https://hpmc12.mobilecenter.io/rest/client/login", customHeaders: [name: 'Content-Type', value: 'application/json'], consoleLogResponseBody: true

         }
}
